[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:fastapi.*:
    ignore::DeprecationWarning:starlette.*:
    ignore::DeprecationWarning:httpx.*:
    ignore::PendingDeprecationWarning:starlette.*:
    ignore::RuntimeWarning:unittest.mock:
